/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package teleporttool;

import java.awt.BorderLayout;
import java.net.URLDecoder;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.scene.web.WebView;
/**
 *
 * @author bcleveland
 */
public class ModuleFrame extends javax.swing.JFrame {

    private Module module;
    private WebView webComponent;
    JFXPanel javafxPanel;
    
    /**
     * Creates new form ModuleFrame
     */
    public ModuleFrame() {
        javafxPanel = new JFXPanel();
        initComponents();
        this.webViewParent.setLayout(new BorderLayout());
        this.webViewParent.add(javafxPanel, BorderLayout.CENTER);
        this.webViewParent.add(javafxPanel);
 
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    public ModuleFrame(Module module) {
        this();
    
        this.module = module;
        
        this.typeTextField.setText(module.getType());
        this.timestampTextField.setText(module.getTimestamp().toString());
        this.durationTextField.setText(module.getDuration().toString());
        this.modifiedTextField.setText(module.getModified());
        this.ttlTextField.setText(module.getTtl().toString());
        this.dataTextArea.setText(URLDecoder.decode(module.getData().toString()));
        this.dataTextArea.setCaretPosition(0);
        this.setTitle("Module ID: " + module.getId().toString());
        
        loadJavaFXScene();
    }
    
  /**
  * Instantiate the JavaFX Components in
  * the JavaFX Application Thread.
  */
  private void loadJavaFXScene(){
    Platform.runLater(new Runnable() {
      @Override
      public void run() {
        BorderPane borderPane = new BorderPane();
        webComponent = new WebView();
        
        webComponent.getEngine().loadContent(URLDecoder.decode(module.getData().toString()));

        borderPane.setCenter(webComponent);
        Scene scene = new Scene(borderPane,320,480);
        javafxPanel.setScene(scene);

      }
    });
  }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webViewParent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timestampTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        modifiedTextField = new javax.swing.JTextField();
        ttlTextField = new javax.swing.JTextField();
        durationTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        webViewParent.setMaximumSize(new java.awt.Dimension(320, 480));
        webViewParent.setMinimumSize(new java.awt.Dimension(320, 480));
        webViewParent.setPreferredSize(new java.awt.Dimension(320, 480));

        javax.swing.GroupLayout webViewParentLayout = new javax.swing.GroupLayout(webViewParent);
        webViewParent.setLayout(webViewParentLayout);
        webViewParentLayout.setHorizontalGroup(
            webViewParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        webViewParentLayout.setVerticalGroup(
            webViewParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dataTextArea.setColumns(20);
        dataTextArea.setLineWrap(true);
        dataTextArea.setRows(5);
        jScrollPane1.setViewportView(dataTextArea);

        jLabel1.setText("type:");

        jLabel2.setText("timestamp:");

        jLabel3.setText("modified:");

        jLabel4.setText("ttl:");

        jLabel5.setText("duration:");

        jLabel6.setText("data:");

        timestampTextField.setEditable(false);
        timestampTextField.setText("jTextField1");

        typeTextField.setEditable(false);
        typeTextField.setText("jTextField2");

        modifiedTextField.setEditable(false);
        modifiedTextField.setText("jTextField3");

        ttlTextField.setEditable(false);
        ttlTextField.setText("jTextField4");

        durationTextField.setEditable(false);
        durationTextField.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeTextField)
                            .addComponent(timestampTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifiedTextField)
                            .addComponent(ttlTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(durationTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webViewParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(timestampTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(modifiedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ttlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webViewParent, javax.swing.GroupLayout.PREFERRED_SIZE, 454, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dataTextArea;
    private javax.swing.JTextField durationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modifiedTextField;
    private javax.swing.JTextField timestampTextField;
    private javax.swing.JTextField ttlTextField;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JPanel webViewParent;
    // End of variables declaration//GEN-END:variables
}
